### ISSUE TITLE
Understand 2025/08/06 nightly benchy regression in KNN indexing

### ISSUE THREAD

**Issue by mikemccand** [apache/lucene#15079]
[Spinoff from [this comment](https://github.com/apache/lucene/pull/14932#issuecomment-3167938331)]

We recently merged a [nice opto to use GroupVarInt instead of VarInt for encoding each node's neighbors list in the HNSW (KNN) graph](https://github.com/apache/lucene/pull/14932).  Benchmarks showed improvements to search latency, which we expect since GroupVarInt decodes four ints at once and puts less branch prediction stress on the CPU.

But oddly nightly vector indexing benchmarks seemed to slow down, on 2025/08/06, and it's not yet obvious why -- it isn't one of the random "glitches" that that recover after a day or two (those are separately annoying!  [`beast3` benchy box is old now](https://blog.mikemccandless.com/2021/01/apache-lucene-performance-on-128-core.html), ~4.5 years, which equates to 135 years in humans years!  (1 computer year = 30 human years)  Maybe it is getting a bit flakey in its later years...).

I'll try to dig some more ... but if I get nowhere (likely!), I think we should temporarily revert GroupVarInt and see if benchy recovers?  Especially because this might become a blocker for 10.3 release...

**Comment by mikemccand** [comment]
It's [this indexing chart](https://benchmarks.mikemccandless.com/indexing.html#MedVectorsIndexTime) (`~1 KB Wikipedia English docs, with KNN Vectors`) that shows the slowdown -- zoom in on the end, annotation `IZ`.

**Comment by rmuir** [comment]
> It's [this indexing chart](https://benchmarks.mikemccandless.com/indexing.html#MedVectorsIndexTime) (`~1 KB Wikipedia English docs, with KNN Vectors`) that shows the slowdown -- zoom in on the end, annotation `IZ`.

<img width="927" height="678" alt="Image" src="https://github.com/user-attachments/assets/e57c2d5b-84cd-48ae-8520-697ad4004cbd" />

I think we shouldn't ignore the forest for the trees here. There is a bigger issue and to me it seems like we should take a step back. Performance has dropped 20x over time.

**Comment by msokolov** [comment]
Yeah those cliffs look terrifying, but I think the two biggest ones at least, were due to changes in the test setup, not to performance regressions in Lucene. There are a bunch of smaller drops that I wonder about tho

**Comment by mikemccand** [comment]
The chart is indeed depressing on first glance!...

9/25/2021 was due to increasing default HNSW `beamWidth` from 16 to 100, 7/17/2023 was from increase vectors from 100 dims to 768 dims (mpnet), then 8/25/2024 was from switching from mpnet to Cohere wikipedia vectors (still 768 dims).

But 4/30/2024 remains unexplained.  It might be [this luceneutil fix](https://github.com/mikemccand/luceneutil/commit/615ff6c75157f395dfbe2b133c67415c81fe5399), which may've been causing messed up Cohere 768 vectors we were testing on up until that point (casting each double into two adjacent messed-up `float32`).  I'll add annot.

I found something really strange about the first drop (8/6/2025) in this issue.  When looking at the indexing output (every 10 K docs) there is a massive discontinuity in the output while building the vectors index:

```
...
Indexer: 23900000 docs (2870.7 sec); 8325.4 docs/sec
Indexer: 23910000 docs (2872.6 sec); 8323.5 docs/sec
Indexer: 23920000 docs (2874.4 sec); 8321.6 docs/sec
Indexer: 23930000 docs (2876.3 sec); 8319.7 docs/sec
Indexer: 23940000 docs (2877.9 sec); 8318.5 docs/sec
Indexer: 23950000 docs (8665.2 sec); 2763.9 docs/sec
Indexer: 23960000 docs (8666.0 sec); 2764.8 docs/sec
Indexer: 23970000 docs (8666.6 sec); 2765.8 docs/sec
Indexer: 23980000 docs (8667.3 sec); 2766.7 docs/sec
Indexer: 23990000 docs (8668.0 sec); 2767.7 docs/sec
Indexer: 24000000 docs (8668.7 sec); 2768.6 docs/sec
...
```

~5787 seconds hang!  This might be CMS back-pressure.  I peeked in kernel logs and don't see any smoking gun, and, the next couple day's runs don't show this odd hang.  I'll turn on InfoStream for this indexing going forwards...

**Comment by mikemccand** [comment]
Oooh the vmstat charts show the horrific "IOWAIT".  [Healthy run (08/05)](https://benchmarks.mikemccandless.com/2025.08.05.18.04.16/fastIndexMediumDocsWithVectors/) and then [unhealthy run (08/06)](https://benchmarks.mikemccandless.com/2025.08.06.18.04.40/fastIndexMediumDocsWithVectors/), and then next [healthy but still slow run (08/07) ](https://benchmarks.mikemccandless.com/2025.08.07.18.04.39/fastIndexMediumDocsWithVectors/), and then [after we went back to `NORMAL` from `RANDOM` io hint (08/08)](https://benchmarks.mikemccandless.com/2025.08.08.18.04.12/fastIndexMediumDocsWithVectors/) -- wow look at the difference in the "Memory Usage" chart.  That's wild -- this sure sounds like [the MGLRU issue](https://github.com/apache/lucene/issues/14408) might be affecting the nightly benchy box? -- under `MADV_RANDOM` the `active` RAM stayed flat as if the costly random swapped in page by page didn't count in the kernel's view as "hot", sheesh.

**Comment by mikemccand** [comment]
The 08/06 run with the huge slowdown shows this odd stack frame in [the allocation profile](https://benchmarks.mikemccandless.com/2025.08.06.18.04.40.html#profiler_1kb_indexing_vectors_12_heap):

```
3.04%         5193M         java.lang.invoke.DirectMethodHandle#allocateInstance() [Inlined code]
                              at java.lang.invoke.DirectMethodHandle$Holder#newInvokeSpecial() [Inlined code]
                              at java.lang.invoke.Invokers$Holder#linkToTargetMethod() [Inlined code]
                              at org.apache.lucene.store.MemorySegmentIndexInput#readGroupVInt() [Inlined code]
                              at org.apache.lucene.util.GroupVIntUtil#readGroupVInts() [Inlined code]
                              at org.apache.lucene.codecs.lucene99.Lucene99HnswVectorsReader$OffHeapHnswGraph#seek() [JIT compiled code]
                              at org.apache.lucene.util.hnsw.UpdateGraphsUtils#computeJoinSet() [JIT compiled code]
                              at org.apache.lucene.util.hnsw.MergingHnswGraphBuilder#updateGraph() [JIT compiled code]
                              at org.apache.lucene.util.hnsw.MergingHnswGraphBuilder#build() [Interpreted code]
                              at org.apache.lucene.util.hnsw.IncrementalHnswGraphMerger#merge() [Interpreted code]
                              at org.apache.lucene.codecs.lucene99.Lucene99HnswVectorsWriter#mergeOneField() [Interpreted code]
                              at org.apache.lucene.codecs.perfield.PerFieldKnnVectorsFormat$FieldsWriter#mergeOneField() [Interpreted code]
```

What is this `Holder#linkToTargetMethod()` and `DirectMethodHandle$Holder#newInvokeSpecial` under `readGroupVInts`?  Why are we allocating method handles when invoking this low level method ...

**Comment by uschindler** [comment]
I have the feeling this allocation profile is caused by this lambda (which was always there): https://github.com/apache/lucene/blob/f0483d3ce99e56ffbe433fc655c16e0bb5d760c2/lucene/core/src/java/org/apache/lucene/store/MemorySegmentIndexInput.java#L457

The problem with MemorySegments is: all code is backed by VarHandles and this could quickly cause wrong inlining decissions as all of this code relies on correct inlining. Looks like a VM bug, so we should nail this down and open an issue. I can help with that. This allocation profile should not be produced by lambdas, so there's clearly some opimization in Hotspot doing the wrong thing. It only allocates ne method handles (and also causes GC pressure) if something goes wrong. That's the risk of the VarHandles in Panama FFI/MemorySegments (and how they are implemented internally).

I'd suggest to reverr the above PR and check again. It looks like it does not works well perfectly with the current code in MMapDir. The code there is a bit tricky but relies stronly on correct inlining, especially regarding that specific lambda.

Uwe

**Comment by uschindler** [comment]
P.S.: Around that time there was also a cleanup of code in MMAPDir, which looks strange (at least the backport to 9.x): https://github.com/apache/lucene/pull/15033 (this caused also strange errors during backporting).

The unused variable had a reason. It looks fine, but this could also cause issues with that code. Best would be to revert the GroupVarInt code and all other code that touched MMapDir.

**Comment by rmuir** [comment]
@uschindler I think the inlining breaks because of @jpountz recent change to introduce "type pollution".

Specifically this line:

```java
// Use ByteBuffersDirectory instead of MMapDirectory to have multiple IndexInput sub-classes used by queries
try (Directory dir = new ByteBuffersDirectory()) {
```
https://github.com/mikemccand/luceneutil/blob/ea81b5d7f6e36bb04ffe7212f7e7129f9f6edc16/src/main/perf/TypePolluter.java#L64-L65

Now during indexing, as soon as 1GB file is encountered, MMapDirectory introduces a third implementation which makes everything go megamorphic.

I'd suggest:
* Remove the two IndexInput implementations in MMapDirectory: there's no longer a 32-bit ByteBuffer limit at play.
* Fix ByteBuffersDirectory (or rename it?) to no longer use ByteBuffers either. This should remove another implementation: it can just be mmap over an anonymous mapping.

**Comment by uschindler** [comment]
> [@uschindler](https://github.com/uschindler) I think the inlining breaks because of [@jpountz](https://github.com/jpountz) recent change to introduce "type pollution".
> 
> Specifically this line:
> 
> // Use ByteBuffersDirectory instead of MMapDirectory to have multiple IndexInput sub-classes used by queries
> try (Directory dir = new ByteBuffersDirectory()) {
> https://github.com/mikemccand/luceneutil/blob/ea81b5d7f6e36bb04ffe7212f7e7129f9f6edc16/src/main/perf/TypePolluter.java#L64-L65

That's fine, but is an issue. The problem here is more different *other* IndexInputs, because:

> Now during indexing, as soon as 1GB file is encountered, MMapDirectory introduces a third implementation which makes everything go megamorphic.
> 
> I'd suggest:
> 
> * Remove the two IndexInput implementations in MMapDirectory: there's no longer a 32-bit ByteBuffer limit at play.

That's not an issue anymore. MMapDirectory only uses the alternate implementation if the file is larger than 16 Gigabytes (due to fragmentation issues). This won't ever happen with default merging policy unless you force merge to mone segment. So basically you will only see one implementation. You can easily see this in the types seen in the profile/heap dump.

> * Fix ByteBuffersDirectory (or rename it?) to no longer use ByteBuffers either. This should remove another implementation: it can just be mmap over an anonymous mapping.

If we do this, then actually Adrien would need to replace the pollution code by some other IndexInput impl (like NIOFSDir). Actually he used ByteBuffersDirectory to actually pollute, so by aligning the polluted impl by another one the pollution goes away and we no longer see what we want to see.

**Comment by uschindler** [comment]
But I agree the type pollution comes into play. But the issue is not two MMapIndexInput implementations, because it only uses one.

**Comment by rmuir** [comment]
> If we do this, then actually Adrien would need to replace the pollution code by some other IndexInput impl (like NIOFSDir). Actually he used ByteBuffersDirectory to actually pollute, so by aligning the polluted impl by another one the pollution goes away and we no longer see what we want to see.

Yes, of course, but then it gets better. We have functionality such as `NRTCachingDirectory` which uses a mix of ByteBuffersDirectory and MMapDirectory. So it seems like a good win if we can make the "ram dir" just be "MMapDirectory over an anonymous mapping"?

**Comment by uschindler** [comment]
Yes, but this was exactly like that before. Mike also used NRTCachingDirectory before. The bigger problem with IndexInputs is that we have many more of them.

In fact the problem with the ByteBuffersDirectory is that is uses multiple buffers behind scenes and not a single one. When you replace that by a MemorySegmentIndexInput on a byte arry or an anonymous mapping (not needed), it will use the Multi-Impl again.

P.S.: In the heap profile there's no MultiSegmentImpl (search for it, you will only find SingleSegmentImpl): https://benchmarks.mikemccandless.com/2025.08.06.18.04.40.html

In addition for the above issue the type pollution is only relevant for the above problem if you call a method which exists in more than zwo implementations. For the above "hot" method `org.apache.lucene.store.MemorySegmentIndexInput#readGroupVInt()` there exists exactly ONE (optimized) implementation in mmapdir and another one in the IndexInput base class.

**Comment by uschindler** [comment]
I think we should remove the callback and lambda completely. The callback was only implemented to get the forward/backward reading of ints from the input using some positional API. It is not nice, see: https://github.com/apache/lucene/pull/12841

We should basically rewrite this to NOT use positional access. If we really need to, we should add a protected helper method in DataInput to help with reading from absolute positions relative to current position.

Basically we need a (protected) method in IndexInput to read an integer relative to the current position but without changing position (which is updated at end).

**Comment by uschindler** [comment]
I have a fix for the stupid lamda code, by using VarHandles directly. So the readVInt callback now directly uses the VarHandle to the ByteBuffer or the MemorySegment (with some adaptions). The PR is still draft, as it needs more documentation, but generally it works. The micro-benchmarks done by @rmuir and myself look like improving the MemorySegment by 25% and removing GC and flakiness. For ByteBuffersDirectory the speed is same as before.

PR: https://github.com/apache/lucene/pull/15089

The problem we are seeing here is due to the stupid *capturing* lambda: The problem is that the referee (the MemorySegment or the ByteBuffer where the data is read from) is not compiled into the lambda code and needs to be captured and bound at runtime. This causes instances of the lambda class to be created on each call and escape analysis does not seem to work well.

This code using VarHandles uses a static final VarHandle that does not need to capture and passes the referee separately as untyped parameter to the `GroupVIntUtil` helper method instead of binding int each time (like capturing lambdas do).

**Comment by uschindler** [comment]
The code will be backported with some adaptions to work around the usual Java 21 preview limitations, but that's easy to do without needing to touch MR-JAR code (see description in PR). But before doing this I'd like to see benchy.

@mikemccand: can you trigger a nightly bench now to speed up turnaround? When will it run next?

Thanks, Uwe

**Comment by uschindler** [comment]
P.S.: Here are the essentials why the new solution is best:

<img width="1080" height="1102" alt="Image" src="https://github.com/user-attachments/assets/924ebcae-648e-4996-9f7d-d51f47cd4062" />

**Comment by mikemccand** [comment]
> The problem we are seeing here is due to the stupid _capturing_ lambda: The problem is that the referee (the MemorySegment or the ByteBuffer where the data is read from) is not compiled into the lambda code and needs to be captured and bound at runtime. This causes instances of the lambda class to be created on each call and escape analysis does not seem to work well.

Annoying.  Does java provide a way to make a `static` lambda?  So that it won't capture the runtime scope it's birthed in?

**Comment by mikemccand** [comment]
> [@mikemccand](https://github.com/mikemccand): can you trigger a nightly bench now to speed up turnaround? When will it run next?

Ugh, last night's run failed for stupid reason (I had left a code mode in nightly benchy git clone).

I just triggered an a-la-cart run ... should show results in ~10 ish hours?

Thank you @uschindler @rmuir and everyone for the super fast turnaround!  Let's cross fingers 🤞 this resolves the performance impact.

**Comment by uschindler** [comment]
> > The problem we are seeing here is due to the stupid _capturing_ lambda: The problem is that the referee (the MemorySegment or the ByteBuffer where the data is read from) is not compiled into the lambda code and needs to be captured and bound at runtime. This causes instances of the lambda class to be created on each call and escape analysis does not seem to work well.
> 
> Annoying. Does java provide a way to make a `static` lambda? So that it won't capture the runtime scope it's birthed in?

You can do this by not referring to any external fields (captures "this") or local variables of calling method. This could be fixed by using a BiFunction-like signature, but it still adds useless abstractions. Using the Varhandle and passing it around is much better and "correct". BTW, the new varhandle code passes the underlying storage as an anonymous extra parameter to the implementation.

**Comment by uschindler** [comment]
> > [@mikemccand](https://github.com/mikemccand): can you trigger a nightly bench now to speed up turnaround? When will it run next?
> 
> Ugh, last night's run failed for stupid reason (I had left a code mode in nightly benchy git clone).
> 
> I just triggered an a-la-cart run ... should show results in ~10 ish hours?
> 
> Thank you [@uschindler](https://github.com/uschindler) [@rmuir](https://github.com/rmuir) and everyone for the super fast turnaround! Let's cross fingers 🤞 this resolves the performance impact.

If that works I can also backport this PR, but it is complicated (due to requirement of Java 22 code and preview mode in Java 21 - damn). See the current pR with analysis. But I have a working solution here, will post a PR after testing with Java 21, 22, 23, 24 of 10.x.

Uwe

**Comment by uschindler** [comment]
Here is the backport: https://github.com/apache/lucene/pull/15093

**Comment by uschindler** [comment]
@mikemccand: What is the timezone of the timestamps on your benchy web page? Is it UTC or something else?

**Comment by uschindler** [comment]
P.S.: If this fixes the problem we know fo sure: The bug with the broken optimizations due to the capturing existed since longer time, it was just not visible due to:
- no call-site pollution
- not used during indexing

If we see a speedup this may also affect queries using GroupVInt encoding. In addition the NIOFSDr and ByteBuffers directory were possibly also affected by the capturing lambda, but I think due to different optimizations, the escape analysis worked fine (I think the capturing lambda with a varhandle inside was tooooo much abstractions for the optimizer). Varhandles are fancy but they require correct optimization too. The whole MemorySegment API relies on Varhandles (everything accessing memory in FFI and large parts of new native ByteBuffer APIs nowadays uses VarHandles behind scenes!).

Capturing Lambdas are not an issue in general, they are only an additional thing that can go wrong. So please don't start and try to avoid capturing lambdas everywhere! The optimizer is good to remove them, so don't worry!!!

Basically we should open an issue in JDK, but I doubt that we can get a reproducer!

**Comment by mikemccand** [comment]
> [@mikemccand](https://github.com/mikemccand): What is the timezone of the timestamps on your benchy web page? Is it UTC or something else?

The charts (e.g. [Indexing](https://benchmarks.mikemccandless.com/indexing.html)) are all EST (Eastern Standard Time), currently UTC-4.

Alas, my a-la-cart build failed -- `ProfileResults` moved -- I [pushed a fix to luceneutil](https://github.com/mikemccand/luceneutil/commit/42ac2e715da4a593f23a75699ff8b14c648ac993) and kicked off another a-la-cart build.

**Comment by dweiss** [comment]
I'm sorry, @mikemccand - I didn't realize this class is used outside of the build system.

**Comment by uschindler** [comment]
Still waiting for results. Did the benchy run fail again?

**Comment by mikemccand** [comment]
> I'm sorry, [@mikemccand](https://github.com/mikemccand) - I didn't realize this class is used outside of the build system.

Oh no worries!  It's alwsys been exciting massaging the heart of nightly benchy... not you fault at all!  And thank you for giving the build tooling so much love...

**Comment by mikemccand** [comment]
> Still waiting for results. Did the benchy run fail again?

Alas, it failed again, having not cleaned up a leftover log file from the prior run.  I just pushed a [fix for that](https://github.com/mikemccand/luceneutil/commit/5b6a67317988bc1da3f7b23031f60ac61999910f), and restarted just now.  Cross fingers again!

**Comment by rmuir** [comment]
> I'm sorry, [@mikemccand](https://github.com/mikemccand) - I didn't realize this class is used outside of the build system.

I didn't either and I think I wrote it. It's still very sad we must write our own CLI to use jmh? Java used to have "hprof" cli option for simple profiling...

Agree with Mike, you can't feel bad about this stuff. Really appreciate the big build cleanups and reworks.

**Comment by dweiss** [comment]
It's getting there, slowly but there is progress I think.

**Comment by mikemccand** [comment]
OK benchy failed again (silly reason), I fixed and start again!  3rd time's the charm?

**Comment by uschindler** [comment]
> OK benchy failed again (silly reason), I fixed and start again! 3rd time's the charm?

I was about to ask! This morning at 8:00 CEST I was already checking, but the timestamp at bottom of page was still freezed.

**Comment by uschindler** [comment]
@mikemccand: As the benchy at least started to run, did if finalize indexing? Maybe we can just inspect the normal log output manually? You can attach the benchmark output and corresponding profile here. /myself does not need fancy graphs for a quick overview.

**Comment by mikemccand** [comment]
> [@mikemccand](https://github.com/mikemccand): As the benchy at least started to run, did if finalize indexing? Maybe we can just inspect the normal log output manually? You can attach the benchmark output and corresponding profile here. /myself does not need fancy graphs for a quick overview.

Phew, I just checked on it -- it is running this exact indexing job RIGHT NOW!

**Comment by uschindler** [comment]
Hi,
I got the new results, from what I see at first:
- many boolean queries got an improvement and restored to the "pre-pollution" state. So It looks like the GroupVInt Varhandle Change and removal of the Lambda helped a lot (see also the problem with the benchmark that @jpountz discovered). Actually in a micro-.benchmark the VarHandle change has a bit of negative impact. See #15104 for details. IMHO, the change is good, although Adrien sees a slowdown (which may be caused by too-short warmup time). <img width="1335" height="614" alt="Image" src="https://github.com/user-attachments/assets/a2f06764-8dae-4ff6-b614-a84c69f87679" />
- I don't see to much change in the indexing time with KNN. I hjave not yet looked at allocation profile. But to me it is a bit slower than before the pollution added by @jpountz. <img width="3055" height="1282" alt="Image" src="https://github.com/user-attachments/assets/16635732-2f44-4a2f-a5a6-21d55910ef60" />

To me the change looks fine, or am I misinterpreting something?

**Comment by uschindler** [comment]
The strange [allocation profile](https://benchmarks.mikemccandless.com/2025.08.21.06.51.27.html#profiler_1kb_indexing_vectors_1_heap) went away, we now only see this for ReadGroupVint:
```
0.04%         1652          java.lang.invoke.LambdaForm$DMH.0x00007ff76d190c00#invokeStatic() [JIT compiled code]
                              at java.lang.invoke.LambdaForm$MH.0x00007ff76d1c5000#invoke() [JIT compiled code]
                              at java.lang.invoke.VarHandleGuards#guard_LJ_I() [Inlined code]
                              at org.apache.lucene.util.GroupVIntUtil#readGroupVInt() [JIT compiled code]
```

This is perfectly normal, although it is not inlined completely here (but this should happen later). This is how it should look like. I have the feeling that the "JIT compiled code" is not yet inlined. But maybe the adoptions using the VarHandleFilters lead to the bad perf in the microbenchmark.

**Comment by easyice** [comment]
The allocation profile looks good. I’ve been adjusting the JMH runtime parameters, but haven’t seen any speedup yet.

**Comment by uschindler** [comment]
I will try to do some changes to the VarHandle code over the weekend. Maybe we can imporve it. To me it is completely strange that we see an improvement here.

I have one guess: Maybe when we completely revert the optimization for MMapDirectory's MemorySegmentIndexInput and the other, the performance will go straight upwards. I have the feeling that we had the slowdown because of the GC pressure and now we have improved and are at the "bad perf" level of #15104. If we would disable the MMapDir/NIOFSDir/ByteBuffers dir optimization completely it could be that Mike's benchamrk gets much faster!

...just guesses.... but this is my only explanation for what we see here!

**Comment by uschindler** [comment]
> `at java.lang.invoke.VarHandleGuards#guard_LJ_I() [Inlined code]`

This is basically the signature of the VarHandle: 2 parameters, one reference (L) and one long (J) and the VarHandle returns an integer (I).

**Comment by uschindler** [comment]
I still wonder why the invoke and invokeStatic are not inlined (which may be the reason for the slow perf in the microbenchmark).

**Comment by uschindler** [comment]
Here is the example for a standard `MemorySegmentIndexInput#readByte()`:

```
0.38%         2071          jdk.internal.foreign.MemorySessionImpl#checkValidStateRaw() [Inlined code]
                              at jdk.internal.misc.ScopedMemoryAccess#getByteInternal() [Inlined code]
                              at jdk.internal.misc.ScopedMemoryAccess#getByte() [Inlined code]
                              at java.lang.invoke.VarHandleSegmentAsBytes#get() [Inlined code]
                              at java.lang.invoke.LambdaForm$DMH.0x00007ff76d191c00#invokeStatic() [Inlined code]
                              at java.lang.invoke.LambdaForm$MH.0x00007ff76d193000#invoke() [Inlined code]
                              at java.lang.invoke.VarHandleGuards#guard_LJ_I() [Inlined code]
                              at jdk.internal.foreign.AbstractMemorySegmentImpl#get() [Inlined code]
                              at org.apache.lucene.store.MemorySegmentIndexInput#readByte() [Inlined code]
                              at org.apache.lucene.codecs.lucene103.PForUtil#decode() [JIT compiled code]
                              at org.apache.lucene.codecs.lucene103.Lucene103PostingsReader$BlockPostingsEnum#refillPositions() [JIT compiled code]
                              at org.apache.lucene.codecs.lucene103.Lucene103PostingsReader$BlockPostingsEnum#nextPosition() [Inlined code]
```

Here you see the Varhandle code is inlined. I have no idea why this does not happen for the GroupVInt code. I have some ideas.

@easyice: Do you think we could change ReadGroupVintUtil to be an instance class instead of purely static. The we could add a getter to IndexInput to retrieve an instance for the given IndexInput that can read and decode IndexInputs. All VarHandles and the delegate would be final fields in that instance and therefor are better to inline. 

I think the whole problem with the lambda and also those VarHandles here is the fact that the JVM cannot assume them to be static (as the captures for the lambda) and/or singletons (the VarHandle is static, but the delegate is passed on each call).

For the microbenchmark it is not an issue at all, because it is totally isolated and the JVM can see that theres only one instance of the class and one type. So the old "lambda" benchmark was fast only because the escape analysis was successful, which is not possible in an environment with multple instances.

I think you can kill the "old" benchmark using the lambda also when you run all benchamrks in the same JVM behind each other, currently it spawns a new JVM for each benchamrk, so it always has a clean set of classes that can be properly inlined. The Varhandle thing has more problems (I agree), but that's again caused by the way we call it. Passing a Varhanle and the Referent as parameter to the method is not easy inlineable.

The main problem of the current code is the "callback", i think we can revisit this. Let me think about it a bit over the weekend.

**Comment by uschindler** [comment]
I reverted the lambda vs. VarHandle fix and give it another try. I hope the benchmarking now works stable, so we can see the results one-by-one. The 4 days of silence of the benchy machine made the analysis very complicated. I know the right track, let's think about it. My idea is to replace the lambda/varhandle by a simple callback instance which is statically allocated! This allows us to optimize in subclasses without adding extra code and add public methods. I also don't like the new Method in IndexInput that is not declared "protected" because its called from the static utility class.

@jpountz: I'd like to move the GroupVIntUtil code regarding the optimization into the DataInput base class as protected method (only available to subclasses) and then we can have a nice lambda-free implementation in subclasses (still using Varhandle), but without adaptions referring to final fields in the implementation class.

I will make a new PR with this approach. This would allow us to minimize the adaption logic and use the VarHandle in a way it is designed for (passing it as method parameter was a bad idea!).

**Comment by uschindler** [comment]
An alternative approach would be to autogenerate the code for the three instances with a simple python script....

**Comment by uschindler** [comment]
Here is another rwwrite of the GroupVInt improvement without any hacks, just plain Lucene API usage.... https://github.com/apache/lucene/pull/15116

**Comment by mikemccand** [comment]
> The 4 days of silence of the benchy machine made the analysis very complicated.

I agree, sorry @uschindler -- benchmarking is hard!  We have some good data points now, four new runs since the wall-of-silence.

> An alternative approach would be to autogenerate the code for the three instances with a simple python script....

Oooh this is my favorite!

> Here is another rwwrite of the GroupVInt improvement without any hacks, just plain Lucene API usage.... [#15116](https://github.com/apache/lucene/pull/15116)

Thanks for all the digging @uschindler!

Unfortunately, another change I did was to enable `InfoStream` when building that vectors index, so that I could generate the segment trace (using `infostream_to_segments.py` and `segments_to_html.py` tools in [luceneutil](https://github.com/mikemccand/luceneutil)).  This was first done in the 08/21 run (that ended wall-of-silence).  InfoStream in the past hasn't changed indexing throughput measurably, so this shouldn't be important, but I wanted to call out for full transparency.

What I learned from that InfoStream, and its [horrifying segment trace](https://githubsearch.mikemccandless.com/nightly-vectors-index.html), is that this indexing run is not healthy -- a huge backlog of merges accumulates, but, they never stall indexing.  Lucene's defaulting to an allowed big backlog here:

```
MS 0 [2025-08-23T01:23:51.617446691Z; main]: initDynamicDefaults maxThreadCount=64 maxMergeCount=69
```

Net/net I'm not so sure I trust this stressful-ish benchy now ... I need to study the segment trace some more (also, this reveals some bugs in segment trace generation).

Anyway, I will disable InfoStream for tonite's run, just to remove that possible variable -- since the indexing is so degenerate, maybe InfoStream is adding too much cost!

**Comment by uschindler** [comment]
Hi Mike,
thanks! There is no run from lat night yet. Last one looks like Aug 24th.
I merged the recent PR yesterday to check what's going on on your side.
Uwe

**Comment by uschindler** [comment]
I did not see much changes since Aug 21th all looks stable, so I don't think the segment trafces (using infostream) is really affecting indexin performance. That's just normal logging! Is a build still ongoing using the current segment tracing, because the one from yestaerday seems to still missing!
It would be nice to see a comparison from your last run on Aug 24th and the state from yesterday evening (CEST time), this commit should be included: https://github.com/apache/lucene/commit/ebfd863ac728f9abfcaa42fec7fce90b62900df5

**Comment by uschindler** [comment]
The new benchamrk is now online. Basically: No changes to the indexing performance. In addition there are also no changes at all for the query performance. https://github.com/apache/lucene/pull/15116 was included in the benchmark, so the GroupVInt encoding has definitely no impact on indexing performance.

To me it looks like we are hunting ghosts.

**Comment by mikemccand** [comment]
> I did not see much changes since Aug 21th all looks stable, so I don't think the segment trafces (using infostream) is really affecting indexin performance.

+1, that is a nice outcome (and agrees with past results).  InfoStream logs are super helpful for debugging indexing issues using [segment tracing](https://githubsearch.mikemccandless.com/long-segments.html).

> To me it looks like we are hunting ghosts.

I think this is likely.  Another couple datapoints and no change.  But it's so annoying for a ghost to decide to appear RIGHT THEN when we merge `GroupVarInt`.  Who knows, it could be something crazy like `GroupVarInt` made merging faster, so this massive backlog of merges finished faster and kicked off further / harder merges, tweaking CPU/IO on the threads doing indexing.
